---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: syrax-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # or latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system/common/bootc-service-override
        destination: /etc/systemd/system/bootc-fetch-apply-updates.service.d/
      - source: system/common/bootc-service-timer-override
        destination: /etc/systemd/system/bootc-fetch-apply-updates.timer.d/
      - source: system/kargs
        destination: /usr/lib/bootc/kargs.d/
      - source: system/bin
        destination: /usr/bin/

  - type: dnf
    install:
      packages:
        - tailscale
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - htop
        - nvtop
        
  - type: script
    scripts:
      - setup-autofirma.sh
      - setup-papirus.sh

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - io.github.kolunmi.Bazaar
          - com.heroicgameslauncher.hgl
          - com.spotify.Client
          - com.rtosta.zapzap
          - io.github.fabrialberio.pinapp
          - page.tesk.Refine
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
        remove:
          - org.gnome.Extensions
      - scope: user

  - type: systemd
    system:
      enabled:
        - bootc-fetch-apply-updates.timer
        - tailscaled.service
      disabled:
        - NetworkManager-wait-online.service

  - type: gnome-extensions
    install:
      - 615   # AppIndicator and KStatusNotifierItem Support
      - 4158  # Gnome 4x UI Improvements
      - 3956  # GNOME Fuzzy App Search
      - 1319  # GSConnect
      - 7     # Removable Drive Menu
      - 3193  # Blur my Shell
      - 6139  # Tailscale QS

  - type: signing # this sets up policy for signing files
